package vyxal.parsing

import vyxal.elements.ElementInformation
import vyxal.elements.Modifier
import vyxal.parsing.TokenType.*
import vyxal.UnopenedGroupException
import vyxal.VyxalException

import scala.collection.mutable.ArrayBuffer
import scala.util.matching.Regex

class LiterateLexer extends LexerCommon:
  private val KeywordLetters = raw"a-zA-Z0-9_<>?!*+\-=&%@~"
  def headIsOpener: Boolean =
    structOpeners.exists((kw, _) =>
      headLookaheadMatch(s"${Regex.quote(kw)}([^$KeywordLetters]|$$)")
    ) || headEqual("{") ||
      lambdaOpeners.exists((kw, _) =>
        headLookaheadMatch(s"${Regex.quote(kw)}([^$KeywordLetters]|$$)")
      )

  def headIsBranch: Boolean =
    branchKeywords.exists(kw =>
      headLookaheadMatch(s"${Regex.quote(kw)}([^$KeywordLetters]|$$)")
    ) || headEqual("|") || headEqual(",") ||
      (headLookaheadMatch(":[^=$!>]") && lastPopped.isBlank())
  def headIsCloser: Boolean =
    closeAllKeywords.exists((kw, _) =>
      headLookaheadMatch(s"${Regex.quote(kw)}([^$KeywordLetters]|$$)")
    ) ||
      endKeywords.exists(kw =>
        headLookaheadMatch(s"${Regex.quote(kw)}([^$KeywordLetters]|$$)")
      )
  private val literateKeywords =
    ElementInformation.elements.values.flatMap(_.keywords)
  private val _tokens = ArrayBuffer[LitToken]()
  private val groups = ArrayBuffer[ArrayBuffer[LitToken]]()
  private var unpackDepth = 0

  private val groupModifierToToken = Map(
    "." -> ((range) => LitToken(MonadicModifier, "⑴", range)),
    ":" -> ((range) => LitToken(DyadicModifier, "⑵", range)),
    ":." -> ((range) => LitToken(TriadicModifier, "⑶", range)),
    "::" -> ((range) => LitToken(TetradicModifier, "⑷", range)),
  )

  private val keywords = Map(
    "close-all" -> TokenType.StructureAllClose,
    "end-all" -> TokenType.StructureAllClose,
    "end-end" -> TokenType.StructureDoubleClose,
  )

  private val endKeywords = List(
    "endfor",
    "end-for",
    "endwhile",
    "end-while",
    "endlambda",
    "end-lambda",
    "end",
  )

  private val branchKeywords = List(
    "->",
    "else:",
    "else",
    "elif",
    "else-if",
    "body",
    "do",
    "branch",
    "then",
    "in",
    "using",
    "no?",
    "=>",
    "from",
    "as",
    "with",
    "given",
    ":and:",
    "has",
    "does",
    "using",
    "on",
  )

  /** Map keywords to their token types */
  private val closeAllKeywords = Map(
    "close-all" -> TokenType.StructureAllClose,
    "end-all" -> TokenType.StructureAllClose,
  )

  private val closeAndFlattenKeywords = List(
    "end-and-flatten",
    "end-flatten",
  )

  private val closeAndHeadKeywords = List(
    "end-and-head",
    "end-head",
  )

  private val lambdaOpeners = Map(
    "lambda" -> StructureType.Lambda,
    "lam" -> StructureType.Lambda,
    "map-lambda" -> StructureType.LambdaMap,
    "map-lam" -> StructureType.LambdaMap,
    "map<" -> StructureType.LambdaMap,
    "filter-lambda" -> StructureType.LambdaFilter,
    "filter-lam" -> StructureType.LambdaFilter,
    "filter<" -> StructureType.LambdaFilter,
    "sort-lambda" -> StructureType.LambdaSort,
    "sort-lam" -> StructureType.LambdaSort,
    "sort<" -> StructureType.LambdaSort,
    "reduce-lambda" -> StructureType.LambdaReduce,
    "reduce-lam" -> StructureType.LambdaReduce,
    "reduce<" -> StructureType.LambdaReduce,
    "fold-lambda" -> StructureType.LambdaReduce,
    "fold-lam" -> StructureType.LambdaReduce,
    "fold<" -> StructureType.LambdaReduce,
    "map-permutations" -> StructureType.LambdaMapPermutations,
    "map-perms" -> StructureType.LambdaMapPermutations,
    "map-permutations<" -> StructureType.LambdaMapPermutations,
    "permutations<" -> StructureType.LambdaMapPermutations,
    "eager-map-lambda" -> StructureType.LambdaMapEager,
    "eager-map-lam" -> StructureType.LambdaMapEager,
    "eager-map<" -> StructureType.LambdaMapEager,
  )

  /** Keywords for opening structures. Has to be a separate map because while
    * all of them have the same [[TokenType]], they have different values
    * depending on the kind of structure
    */
  private val structOpeners = Map(
    // These can't go in the big map, because that's autogenerated
    "yes?" -> StructureType.Ternary,
    "?" -> StructureType.Ternary,
    "if" -> StructureType.IfStatement,
    "for" -> StructureType.For,
    "for<" -> StructureType.For,
    "do-to-each" -> StructureType.For,
    "each-as" -> StructureType.For,
    "while" -> StructureType.While,
    "while<" -> StructureType.While,
    "relation<" -> StructureType.GeneratorStructure,
    "generate-from<" -> StructureType.GeneratorStructure,
    "generate<" -> StructureType.GeneratorStructure,
  )

  private val NUMBER_START_REGEX = "\\d[^<>!*+\\-=&%@~A-Za-z]"
  private val NEGATIVE_NUMBER_START_REGEX = "-[1-9]"
  private val DECIMAL_SEPARATOR = "."
  private val KEYWORD_START_SYMBOLS = "<>!*+-=&%@~"
  private val DOUBLE_QUOTES = "\""
  private val GROUP_OPEN = "("
  private val GROUP_CLOSE = ")"
  private val GROUP_MODIFIER_REGEX = ":[.:]"
  private val GROUP_MODIFIER_SYMBOLS = ".:"
  private val NEWLINE = "\n"
  private val SYMBOLIC_LAMBDA_OPEN = "{"
  private val SYMBOLIC_STRUCTURE_CLOSE = "}"
  private val SPECIAL_CLOSER_REGEX = "\\}#[fh]"
  private val SYMBOLIC_STRUCTURE_CLOSE_AND_FLATTEN = "}#f"
  private val SYMBOLIC_STRUCTURE_CLOSE_AND_HEAD = "}#h"
  private val BRANCH_CHARACTER = "|"
  private val DOUBLE_CLOSE_KEYWORD = "end-end"
  private val GET_VARIABLE_REGEX = "\\$([^@:.]|$)"
  private val VARIABLE_UNPACK_SIGIL = ":=["
  private val VARIABLE_SET_SIGIL = ":="
  private val CONSTANT_SET_SIGIL = ":!="
  private val AUGMENTED_ASSIGN_SIGIL = ":>"
  private val COMMAND_SYMBOL_SIGIL = "$@"
  private val ORIGINAL_COMMAND_SIGIL = "$."
  private val DEFINE_KEYWORD = "define"
  private val DEFINE_ELEMENT_KEYWORD = "element"
  private val DEFINE_MODIFIER_KEYWORD = "modifier"
  private val RECORD_KEYWORD = "record"
  private val EXTENSION_KEYWORD = "extension"
  private val FUNCTION_CALL_SUGAR_CHAR = "`"
  private val LIT_LIST_OPEN = "["
  private val LIT_LIST_CLOSE = "]"
  private val SBCS_NEGATIVE_SIGN = "_"
  private val NEGATIVE_SIGN = "-"
  private val ALLOWED_KEYWORD_SYMBOLS = "_<>?!*+\\-=&%@"
  private val EXTENSION_GIVEN_KEYWORD = "given"

  def lex(program: String): Seq[Token] =
    programStack.pushAll(program.reverse.map(_.toString))
    while programStack.nonEmpty do
      if unpackDepth > 0 then
        if headIsLetter then
          val nameIndex = index
          val name = simpleName()
          addToken(TokenType.Param, name, Range(nameIndex, index))
        else if headEqual(LIT_LIST_OPEN) then
          pop()
          addToken(TokenType.StructureOpen, LIST_OPEN, Range(index, index))
          unpackDepth += 1
        else if headEqual(LIT_LIST_CLOSE) then
          pop()
          addToken(TokenType.StructureAllClose, LIST_CLOSE, Range(index, index))
          unpackDepth -= 1
        else if headEqual(BRANCH_CHARACTER) || headEqual(",") then
          pop()
          addToken(TokenType.Branch, BRANCH_CHARACTER, Range(index, index))
        else pop()
      else if (headIsDigit && headLookaheadMatch(NUMBER_START_REGEX)) ||
        headLookaheadMatch(NEGATIVE_NUMBER_START_REGEX) ||
        headEqual(DECIMAL_SEPARATOR)
      then numberToken
      else if safeCheck(c =>
          c.length == 1 &&
            (c.head.isLetter || c.head.isDigit ||
              KEYWORD_START_SYMBOLS.contains(c))
        )
      then keywordToken
      else if headEqual(DOUBLE_QUOTES) then stringToken(true)
      else if headEqual(GROUP_OPEN) then
        eat(GROUP_OPEN)
        groups += ArrayBuffer[LitToken]()
        if headLookaheadMatch(GROUP_MODIFIER_REGEX) then
          addToken(groupModifierToToken(pop(2))(Range(index, index)))
        else if headIn(GROUP_MODIFIER_SYMBOLS) then
          addToken(groupModifierToToken(pop(1))(Range(index, index)))
      else if headEqual(GROUP_CLOSE) then
        if groups.nonEmpty then
          val group = groups.last
          groups.dropRightInPlace(1)
          addToken(
            LitToken(Group, group.toSeq, Range(index, index))
          )
          eat(GROUP_CLOSE)
        else throw new UnopenedGroupException(index)
      else if headEqual(NEWLINE) then quickToken(Newline, NEWLINE)
      else if headIsWhitespace then pop(1)
      else if headEqual(SYMBOLIC_LAMBDA_OPEN) ||
        lambdaOpeners.contains(programStack.head)
      then
        val lambdaKeyword = pop()
        val lambdaType =
          lambdaOpeners.getOrElse(lambdaKeyword, StructureType.Lambda)

        addToken(
          LitToken(
            TokenType.StructureOpen,
            lambdaType.open,
            Range(index, index),
          )
        )
        lambdaParameters
      else if structOpeners.contains(programStack.head) then
        val tempRange = Range(index, index)
        addToken(TokenType.StructureOpen, structOpeners(pop()).open, tempRange)
      else if headIsBranch then quickToken(TokenType.Branch, BRANCH_CHARACTER)
      else if endKeywords.contains(programStack.head) ||
        (headEqual(SYMBOLIC_STRUCTURE_CLOSE) &&
          !headLookaheadMatch(SPECIAL_CLOSER_REGEX))
      then quickToken(TokenType.StructureClose, SYMBOLIC_STRUCTURE_CLOSE)
      else if headEqual(DOUBLE_CLOSE_KEYWORD) then
        quickToken(TokenType.StructureDoubleClose, STRUCTURE_DOUBLE_CLOSE)
      else if closeAndFlattenKeywords.contains(programStack.head) ||
        headLookaheadEqual(SYMBOLIC_STRUCTURE_CLOSE_AND_FLATTEN)
      then
        quickToken(TokenType.StructureCloseAndFlatten, STRUCTURE_FLATTEN_CLOSE)
      else if closeAndHeadKeywords.contains(programStack.head) ||
        headLookaheadEqual(SYMBOLIC_STRUCTURE_CLOSE_AND_HEAD)
      then
        quickToken(TokenType.StructureCloseAndHead, STRUCTURE_FIRST_ITEM_CLOSE)
      else if closeAllKeywords.contains(programStack.head) then
        quickToken(TokenType.StructureAllClose, STRUCTURE_ALL_CLOSE)
      else if headLookaheadMatch(GET_VARIABLE_REGEX) then
        pop()
        getVariableToken
      else if headLookaheadEqual(VARIABLE_UNPACK_SIGIL) then
        quickToken(TokenType.UnpackTrigraph, "#:[")
        unpackDepth = 1
      else if headLookaheadEqual(VARIABLE_SET_SIGIL) then
        pop(2)
        setVariableToken
      else if headLookaheadEqual(CONSTANT_SET_SIGIL) then
        pop(3)
        setConstantToken
      else if headLookaheadEqual(AUGMENTED_ASSIGN_SIGIL) then
        pop(2)
        augmentedAssignToken
      else if headLookaheadEqual(COMMAND_SYMBOL_SIGIL) then
        pop(2)
        commandSymbolToken
      else if headLookaheadEqual(ORIGINAL_COMMAND_SIGIL) then
        pop(2)
        originalCommandToken
      else if headLookaheadEqual(DEFINE_KEYWORD) then customDefinitionToken
      else if headLookaheadEqual(RECORD_KEYWORD) then
        pop()
        defineRecordToken
      else if headLookaheadEqual(EXTENSION_KEYWORD) then
        pop()
        defineExtensionToken
      else if headEqual(FUNCTION_CALL_SUGAR_CHAR) then
        pop()
        addToken(TokenType.FunctionCall, simpleName(), Range(index, index))
        eat(FUNCTION_CALL_SUGAR_CHAR)
      else if headEqual(LIT_LIST_OPEN) then
        pop()
        addToken(TokenType.ListOpen, LIST_OPEN, Range(index, index))
      else if headEqual(LIT_LIST_CLOSE) then
        pop()
        addToken(TokenType.ListClose, LIST_CLOSE, Range(index, index))
      else if headLookaheadEqual(COMMENT) then
        while safeCheck(c => c != NEWLINE && c != "\r") do pop()
      else
        for c <- pop() do
          addToken(
            LitToken(TokenType.Command, c.toString, Range(index, index))
          )
          index += 1
      end if
    end while
    // Flatten _tokens into tokens

    for token <- flattenTokens(_tokens.toSeq) do tokens += token.toNormal
    tokens.toSeq
  end lex

  def flattenTokens(tokens: Seq[LitToken]): Seq[LitToken] =
    val flattened = ArrayBuffer[LitToken]()
    for token <- tokens do
      token.tokenType match
        case Group =>
          val group = token.value.asInstanceOf[Seq[LitToken]]
          val flattenedGroup = flattenTokens(group)
          flattened ++= flattenedGroup
        case _ => flattened += token
    flattened.toSeq
  def addToken(token: LitToken): Unit =
    if groups.nonEmpty then groups.last += token
    else _tokens += token

  def addToken(tokenType: TokenType, value: String, range: Range): Unit =
    addToken(LitToken(tokenType, value, range))

  def lastToken: LitToken =
    if groups.nonEmpty then
      groups.last.lastOption.getOrElse(LitToken(Empty, "", Range.fake))
    else _tokens.lastOption.getOrElse(LitToken(Empty, "", Range.fake))

  def dropLastToken(): Unit =
    if groups.nonEmpty then groups.last.dropRightInPlace(1)
    else _tokens.dropRightInPlace(1)

  private def keywordToken: Unit =
    val start = index
    val keyword = StringBuilder()
    if !safeCheck(c =>
        c.head.isLetterOrDigit || ALLOWED_KEYWORD_SYMBOLS.contains(c)
      )
    then return

    while safeCheck(c =>
        c.head.isLetterOrDigit || ALLOWED_KEYWORD_SYMBOLS.contains(c) ||
          (c == ":" &&
            keyword.lastOption
              .flatMap(c => Some(c.isLetterOrDigit))
              .getOrElse(false))
      )
    do keyword ++= pop(1)
    val value = removeDoubleNt(keyword.toString())
    if isKeyword(value) then
      addToken(
        LitToken(
          Command,
          getSymbolFromKeyword(value),
          Range(start, index),
        )
      )
    else if isKeyword(value.stripSuffix("n't")) then
      addToken(
        LitToken(NegatedCommand, value, Range(start, index))
      )
    else if isModifier(value) then
      val mod = getModifierFromKeyword(value)
      val name = mod.symbol
      val tokenType = mod.numberOfElements match
        case 1 => TokenType.MonadicModifier
        case 2 => TokenType.DyadicModifier
        case 3 => TokenType.TriadicModifier
        case 4 => TokenType.TetradicModifier
        case _ => TokenType.SpecialModifier
      addToken(LitToken(tokenType, name, Range(start, index)))
    else programStack.push(value)
    end if
  end keywordToken

  private def removeDoubleNt(word: String): String =
    var temp = word
    while temp.endsWith("n'tn't") do temp = temp.stripSuffix("n'tn't")
    temp

  private def isKeyword(word: String): Boolean =
    literateKeywords.toSet.contains(word)

  private def isModifier(word: String): Boolean =
    ElementInformation.modifiers.exists((_, mod) => mod.keywords.contains(word))

  private def getSymbolFromKeyword(word: String): String =
    ElementInformation.symbolForElement(word).getOrElse(word)

  private def getModifierFromKeyword(word: String): Modifier =
    ElementInformation.modifiers.values
      .find(_.keywords.contains(word))
      .getOrElse(throw VyxalException(s"Modifier $word not found"))

  private def numberToken: Unit =
    val rangeStart = index
    // Check the single zero case
    if headLookaheadMatch("0[^.]") then
      val zeroToken = LitToken(TokenType.Number, "0", Range(index, index))
      pop(1)
      addToken(zeroToken)
    else
      addToken(
        LitToken(
          TokenType.Number,
          decimalNumber(),
          Range(rangeStart, index),
        )
      )

  private def simpleNumber(): String =
    val numberVal = StringBuilder()
    while safeCheck(c => c.head.isDigit || c == SBCS_NEGATIVE_SIGN) do
      if headEqual(SBCS_NEGATIVE_SIGN) then pop()
      else numberVal ++= s"${pop()}"
    numberVal.toString()

  private def decimalNumber(): String =
    val negative = headEqual(NEGATIVE_SIGN)
    if negative then pop()
    val tokenVal = StringBuilder()
    // Handle headless decimal first
    if headEqual(DECIMAL_SEPARATOR) then
      tokenVal ++= pop()
      if safeCheck(c => c.head.isDigit) then tokenVal ++= simpleNumber()
    // A normal number
    else if safeCheck(c => c.head.isDigit) then
      tokenVal ++= simpleNumber()
      // Could also a decimal number
      if headEqual(DECIMAL_SEPARATOR) then
        tokenVal ++= pop()
        // If there's a digit after the decimal, add it
        if safeCheck(c => c.head.isDigit) then tokenVal ++= simpleNumber()
    s"${tokenVal.toString()}${if negative then SBCS_NEGATIVE_SIGN else ""}"
  end decimalNumber

  protected def defineExtensionToken: Unit =
    val rangeStart = index
    eatWhitespace()
    val name =
      if headEqual(".") then
        pop()
        s".${simpleName()}"
      else simpleName()
    addToken(
      TokenType.DefineExtension,
      "",
      Range(rangeStart, index),
    )
    addToken(
      TokenType.Param,
      name,
      Range(rangeStart, index),
    )
    eatWhitespace()
    if headLookaheadEqual(EXTENSION_GIVEN_KEYWORD) then
      val givenStart = index
      eat(EXTENSION_GIVEN_KEYWORD)
      addToken(TokenType.Branch, BRANCH_CHARACTER, Range(givenStart, index))

      // Get the arguments and put them into tokens
      var arity = 0
      while !headIsBranch && !headEqual(",") do // Loop until the implementation
        eatWhitespace()
        // Read the name of the argument to the extension
        val argNameStart = index
        val argName = simpleName()
        addToken(
          TokenType.Param,
          argName,
          Range(argNameStart, index),
        )
        eatWhitespace()
        // Read the type of the argument to the extension
        quickToken(TokenType.ExtensionTypeSeparator, EXTENSION_TYPE_SEPARATOR)
        eatWhitespace()
        val argTypeStart = index
        val argType =
          if headEqual(EXTENSION_ANY_TYPE) then pop() else simpleName()
        addToken(
          TokenType.Param,
          argType,
          Range(argTypeStart, index),
        )
        arity += 1
        // Consume any optional comma
        if headEqual(",") then pop()
        eatWhitespace()
      end while
    end if
  end defineExtensionToken

  private def customDefinitionToken: Unit =
    val rangeStart = index
    pop()
    addToken(
      LitToken(
        TokenType.StructureOpen,
        "#::",
        Range(rangeStart, index),
      )
    )
    eatWhitespace()
    if !headLookaheadMatch(
        s"($DEFINE_ELEMENT_KEYWORD|$DEFINE_MODIFIER_KEYWORD)"
      )
    then
      throw VyxalException(
        s"Invalid definition type. Expected \"$DEFINE_ELEMENT_KEYWORD\" or \"$DEFINE_MODIFIER_KEYWORD\""
      )
    val definitionType = pop().toUpperCase()
    while !headIsWhitespace do pop()
    eatWhitespace()
    val nameRangeStart = index
    val name = simpleName()

    addToken(
      LitToken(
        TokenType.Param,
        s"$definitionType$name",
        Range(nameRangeStart, index),
      )
    )

  end customDefinitionToken

  lazy val mapping: Map[String, String] =
    ElementInformation.elements.values.view.flatMap { elem =>
      elem.keywords.map(_ -> elem.symbol)
    }.toMap ++
      ElementInformation.modifiers.values.view.flatMap { mod =>
        mod.keywords.map(_ -> mod.symbol)
      }.toMap ++
      keywords.map { (kw, typ) => kw -> typ.canonicalSBCS.get }.toMap ++
      endKeywords.map(_ -> TokenType.StructureClose.canonicalSBCS.get).toMap ++
      branchKeywords.map(_ -> TokenType.Branch.canonicalSBCS.get).toMap ++
      (lambdaOpeners ++ structOpeners).map { (kw, typ) => kw -> typ.open }
end LiterateLexer
