name: deploy-to-pa
on:
  push:
    branches: [ production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          curl -X POST -H "X-funky-password: ${{ secrets.FUNKY_PASSWORD }}" "https://vyxal.pythonanywhere.com/update" -fsS
